#!/bin/bash -e
#
# Copyright 2016, Intel Corporation
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in
#       the documentation and/or other materials provided with the
#       distribution.
#
#     * Neither the name of the copyright holder nor the names of its
#       contributors may be used to endorse or promote products derived
#       from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
#
# libpmempool_replica_transform_cplx/TEST0 -- test for checking replica
# transform for complex poolset
#
export UNITTEST_NAME=libpmempool_replica_transform_cplx/TEST0
export UNITTEST_NUM=0

. ../unittest/unittest.sh

require_fs_type pmem any

setup

LOG=out${UNITTEST_NUM}.log
LOG_TEMP=out${UNITTEST_NUM}_part.log
rm -rf $LOG && touch $LOG
rm -rf $LOG_TEMP && touch $LOG_TEMP

TRANS_EXE=../libpmempool_repl_transform/libpmempool_repl_transform
LAYOUT=OBJ_LAYOUT
POOLSET_IN=$DIR/poolset_in.set
POOLSET_OUT=$DIR/poolset_out.set
M=$(( 1024 * 1024 ))


declare FILES_IN=( "f1" "f2" "f3" "f4" "f5" "f6" "f7" "f8" "f9" "f10" )
declare FILES_IN_SIZE=( "20M" "20M" "20M" "30M" "30M" "30M" "20M"
	"30M" "20M" "40M" )

file_size_20M_4K=20484K
declare FILES_OUT=( "f1" "f2_new" "f3" "f4" "f5" "f6" "f6_sec" "f7" "f8" "f9"
	"f10" )
declare FILES_OUT_SIZE=( "20M" "20M" "20M" "20M" "30M" "20M"
	$file_size_20M_4K "20M" "20M" "30M" "40M" )

# Create poolset
create_poolset ${POOLSET_IN}\
	${FILES_IN_SIZE[0]}:$DIR/${FILES_IN[0]}:z:${FILES_IN_SIZE[0]}:0777\
	${FILES_IN_SIZE[1]}:$DIR/${FILES_IN[1]}:z:${FILES_IN_SIZE[1]}:0777\
	${FILES_IN_SIZE[2]}:$DIR/${FILES_IN[2]}:z:${FILES_IN_SIZE[2]}:0777\
	${FILES_IN_SIZE[3]}:$DIR/${FILES_IN[3]}:z:${FILES_IN_SIZE[3]}:0777\
	${FILES_IN_SIZE[4]}:$DIR/${FILES_IN[4]}:z:${FILES_IN_SIZE[4]}:0777\
	${FILES_IN_SIZE[5]}:$DIR/${FILES_IN[5]}:z:${FILES_IN_SIZE[5]}:0777\
	${FILES_IN_SIZE[6]}:$DIR/${FILES_IN[6]}:z:${FILES_IN_SIZE[6]}:0777\
	${FILES_IN_SIZE[7]}:$DIR/${FILES_IN[7]}:z:${FILES_IN_SIZE[7]}:0777\
	${FILES_IN_SIZE[8]}:$DIR/${FILES_IN[8]}:z:${FILES_IN_SIZE[8]}:0777\
	${FILES_IN_SIZE[9]}:$DIR/${FILES_IN[9]}:z:${FILES_IN_SIZE[9]}:0777


# Create only poolset file
echo PMEMPOOLSET >> $POOLSET_OUT
echo -e ${FILES_OUT_SIZE[0]} $DIR/${FILES_OUT[0]} >> $POOLSET_OUT
echo -e ${FILES_OUT_SIZE[1]} $DIR/${FILES_OUT[1]} >> $POOLSET_OUT
echo -e ${FILES_OUT_SIZE[2]} $DIR/${FILES_OUT[2]} >> $POOLSET_OUT
echo -e ${FILES_OUT_SIZE[3]} $DIR/${FILES_OUT[3]} >> $POOLSET_OUT
echo -e ${FILES_OUT_SIZE[4]} $DIR/${FILES_OUT[4]} >> $POOLSET_OUT
echo -e ${FILES_OUT_SIZE[5]} $DIR/${FILES_OUT[5]} >> $POOLSET_OUT
echo -e ${FILES_OUT_SIZE[6]} $DIR/${FILES_OUT[6]} >> $POOLSET_OUT
echo -e ${FILES_OUT_SIZE[7]} $DIR/${FILES_OUT[7]} >> $POOLSET_OUT
echo -e ${FILES_OUT_SIZE[8]} $DIR/${FILES_OUT[8]} >> $POOLSET_OUT
echo -e ${FILES_OUT_SIZE[9]} $DIR/${FILES_OUT[9]} >> $POOLSET_OUT
echo -e ${FILES_OUT_SIZE[10]} $DIR/${FILES_OUT[10]} >> $POOLSET_OUT


expect_normal_exit $PMEMPOOL$EXESUFFIX create --layout=$LAYOUT\
	obj $POOLSET_IN
cat $LOG >> $LOG_TEMP


off0=$((5 * $M))
off1=$((25 * $M))
off2=$((45 * $M))
off3=$((75 * $M))
off4=$((105 * $M))
off5=$((135 * $M))
off6=$((155 * $M))
off7=$((185 * $M))
off8=$((205 * $M))
off9=$((225 * $M))

# Write some data at offsets
for i in `seq 0 9`;
do
	vname="off$i"
	expect_normal_exit ./libpmempool_repl_transform_cplx_mod\
	-w -s 16 -l $LAYOUT -d "TestDataa_"$vname -o ${!vname} $POOLSET_IN
	cat $LOG >> $LOG_TEMP
done

expect_normal_exit $TRANS_EXE$EXESUFFIX\
	-o $POOLSET_OUT $POOLSET_IN >> $LOG
cat $LOG >> $LOG_TEMP

# Check copied data
for i in `seq 0 9`;
do
	vname="off$i"
	expect_normal_exit ./libpmempool_repl_transform_cplx_mod\
	-l $LAYOUT -s 16 -o ${!vname} $POOLSET_OUT
	cat $LOG >> $LOG_TEMP
done

# Check metadata by pmempool info
for NAME in ${FILES_OUT[*]}
do
	expect_normal_exit $PMEMPOOL$EXESUFFIX info $DIR/$NAME >> $LOG_TEMP
done

mv $LOG_TEMP $LOG
check

pass
